name: lein-deploy-snapshot
on:
  push:
    branches:
    - "snapshot"
jobs:
  pipeline:
    name: Lein Deploy Snapshot
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      id: checkout
      uses: actions/checkout@v3
    - name: Save Credentials
      id: save_credentials
      run: |
        mkdir -p "$HOME/.lein"
        echo "CLOJARS_CREDS" > $HOME/.lein/credentials.clj
        cat $HOME/.lein/credentials.clj
      env:
        CLOJARS_CREDS: ${{ secrets.CLOJARS_CREDENTIALS }}
    - name: Setup Leiningen
      id: setup_leiningen
      uses: oxr463/setup-leiningen@0.0.1
    - name: Publish Snapshot
      id: publish_snapshot
      run: |
        lein deploy clojars
