name: lein-deploy-release
on:
  push:
    branches:
    - "main"
jobs:
  pipeline:
    name: Lein Deploy Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      id: checkout
      uses: actions/checkout@v3
    - name: Setup Leiningen
      id: setup_leiningen
      uses: oxr463/setup-leiningen@0.0.1
    - name: Publish Release
      id: publish_release
      run: |
        lein release
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
