name: lein-deploy-release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  pipeline:
    name: Lein Deploy Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      id: checkout
      uses: actions/checkout@v3
    - name: Setup Leiningen
      id: setup_leiningen
      uses: oxr463/setup-leiningen@0.0.1
    - name: Publish Release
      id: publish_release
      run: |
        GIT_TAG_VERSION="${GITHUB_REF#refs/tags/v}"
        LEIN_PROJECT_VERSION="$(lein update-in :version pr -- version | cut -d '"' -f 2)"
        if [[ "$GIT_TAG_VERSION" == "$LEIN_PROJECT_VERSION" ]]; then
            lein deploy releases
        else
            >&2 echo "git tag version ($GIT_TAG_VERSION) does not equal lein project version ($LEIN_PROJECT_VERSION)"
            exit 1
        fi
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
